### ISSUE TITLE
Mekanism OreDict Changes

### ISSUE THREAD

**Issue by TwoTailedFox** [draknyte1/GTplusplus#185] opened 2018-01-01 13:07 UTC
In GT++ 1.6.99, the mods correctly strips Mekanism items of their Forge Ore Dictionary entries, which means that the Mekanism Ore and Circuits are useless for GregTech progression.

In GT++ 1.6.103 and GT++ 1.6.110, this modification is no longer in effect, and Mekanism circuits and ore can freely be used by GregTech.

Issue currently ongoing, reverting back to GT++ 1.6.99 restores this change.

GregTech 05.09.32pre1
IC2 2.2.827-experimental
GT++ Single Player
Issue Class: Minor

**Comment by draknyte1** [comment] 2018-02-04 18:32
Couldn't reproduce this issue.
User said issue has been resolve since 1.7.0-preX.

Closing for the time being.

**Closed by draknyte1** 2018-02-04 18:32 UTC
Labels: To investigate, bug, major
