### ISSUE TITLE
Void ore miner suggestion

### ISSUE THREAD

**Issue by 0lafe** [draknyte1/GTplusplus#378] opened 2018-09-14 03:49 UTC
GT version 5.09.32.36
GT++ version 1.7.02.09
GTNH 2.0.5.1

Right now there's no void ore miner from what I can tell, at least not functional. I'm not sure if you already know how you want it to work, but I have an idea to make it perticularly good for gtnh servers, and just generally good. 

Having it mine what's in the dimension you're in, but if you're not getting anything from the dimension besides the location, why not let it work anywhere but have some other way to get the ores. I think it would be cool if you could put a hatch on it or something, then put some ores in that, and it will only mine the ores you tell it to. If it did 1 ore/tick then if there's 30 ores, every tick it just randomly picks one. However, it would be nice to have the amount of ores not be locked to a certain number. So if you need tons of copper, just only tell it to mine copper ore and every tick it'll be copper. Would be nice for things like the new naq reactor to be able to give it a specified output of naquadria. Also would totally be useful for bismuth fusion as a side note. 

It could do something where it decreases in speed if you want to use less ores. Maybe up to 4x if you have 1. 

I think that would be balanced at least on NH, but maybe there's something in normal GT that would get busted with this, I don't know. In NH there's no one dimension that has everything you need, so if the miner is dimension specific you'll have to put at least 1 in a bunch of dimensions and get a bunch of ores you don't want (unless I'm the only one not struggling for grosollar and bauxite when there's pure aluminum and titanium ore in the same place). For speed it should probably be a decent amount slower than the mining speed of the enderquarry, as that has to go through tons of non ore blocks so it'll be much slower even if the void miner mines a little slower.

**Comment by 0lafe** [comment] 2018-09-14 06:34
>It's already planned to only pull ores from the dimensions that it's in. I've got a command that's available for OPs that dumps ore from that dimension, which is the same code the multi will use. (Made a command to test the code)

:( 

>I can make a new set of hatches and cable type blocks which can output special energy from the Naq reactor to power this directly. Thoughts?

If you do need to have it in the dimension that the ores come from, then either it needs some kind of interdimensional transport or not that, because 1 naq reactor per miner seems excessive. Power seems fine, also considering I don't really plan on making the large naq gen, but the void miner is a semi integral part to end game. If it didn't need to be in the dimension then I guess that's fine but I'm not sure if it's needed

**Comment by Scottishprog** [comment] 2018-09-16 03:35
Just from a server load standpoint... I would encourage a void miner of some sort.

As for dimension locking... have a dim chip, made from some ore unique to that  dimension.
Then have another slot/input bus, where you use ore samples to specify output.
Have the output proportional to the amount of a ore in the input bus. 
(Want more copper ore?  add to the copper ore stack....)

**Comment by draknyte1** [comment] 2018-09-16 03:37
Duplicate of https://github.com/draknyte1/GTplusplus/issues/369.

**Closed by draknyte1** 2018-09-16 03:37 UTC

**Comment by draknyte1** [comment] 2018-09-16 03:42
I don't know why you guys are making suggestions, when I added it ages ago and have already decided it's dimension locked as this is the easiest way to support 4 totally different ore generators. (5.07, 5.08, 5.09, GT:GTNH),

>Part of this is it needs to appeal more than the ender quarry, but please don't do that by making it super fast. The enderquarry is already pretty much faster than you would ever need, it's just very inconvenient. Partially because you can't make better ones you just end up having like 16 of them scattered around, and partially because they each need to be in the dimension that they're mining.

I don't mod to make a Better X than Mod Y.
I Mod to add content that fits into GT++ & GT 5.08/09, with GTNH not considered.
If the Enderquarry is fast, cool, it still requires real ores to be mined, so unless you've got MFR, you have no 'free ore miner', which is why this exists.
