### ISSUE TITLE
Remove Cutting Machine air block requirement

### ISSUE THREAD

**Issue by Highbeam** [draknyte1/GTplusplus#375] opened 2018-09-11 15:41 UTC
# Issue Title  
In 2.0.5.1 the cutting machine still needs air blocks in the 9 blocks in front of it.

Placing anything in front will make the multiblock change to incomplete.

**Comment by draknyte1** [comment] 2018-09-11 15:43
Duplicate of https://github.com/draknyte1/GTplusplus/issues/348#issuecomment-420320216

**Closed by draknyte1** 2018-09-11 15:43 UTC
