### ISSUE TITLE
Zhuhai fishing port doesnt validate structure

### ISSUE THREAD

**Issue by crszpth** [draknyte1/GTplusplus#361] opened 2018-08-27 12:43 UTC
## Expected Behavior
Built a 9x3x9 structure with the required hatches and buses to form the fishing pond multiblock.

## Current Behavior
The controller gives an incomplete structure error. A few things I tried, looking at the attached pictures:

- moved the controller on another side of the multiblock (right side), the blocks on the edge of the multiblock formed but not the ones on the inner casing, it still gives an incomplete structure.
- moved the controller on another side of the multiblock (right side) and all other blocks on an edge, all blocks formed but still incomplete structure.

![2018-08-27_13 50 12](https://user-images.githubusercontent.com/42740104/44660229-50175700-aa07-11e8-88fc-19382185cadb.png)
![2018-08-27_13 54 07](https://user-images.githubusercontent.com/42740104/44660199-383fd300-aa07-11e8-933b-76d68ad4d46b.png)

## Steps to Reproduce (for bugs)
Reproducible on GTNH v. 2.0.4.8 while trying to build the fishing pond.
Tried on an old save on GTNH v. 2.0.4.6 and the bug is absent.

## Game Environment
Include as many relevant details about the game environment or modpack you experienced the bug in/on.
If you are using a Modpack:
 * Modpack Name: GTNH
 * Version used: 2.0.4.8

Also include:
 * Gregtech version: 5.09.32.32
 * IC2 version: 2.2.828a-experimental
 * Java version: jre1.8.0_181
 * Operating System: Win 10

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [x]    Single Player?
 - [ ]    Multi Player?

**Comment by draknyte1** [comment] 2018-08-27 13:00
Duplicate of https://github.com/draknyte1/GTplusplus/issues/336.

Structure code for Zhuhai hasn't changed since before April, so the bug definitely exists in the older versions as far back as it's been in GTNH. The difference will be which direction you're facing, as it may form NS but not EW. Please move any further findings to the original issue.

**Closed by draknyte1** 2018-08-27 13:00 UTC
