### ISSUE TITLE
Alloy Blast Smelter weirdness [1.6.110-final & Self compiled master + #196]

### ISSUE THREAD

**Issue by mitchej123** [draknyte1/GTplusplus#198] opened 2018-01-29 01:56 UTC
**Gregtech Version** - GTNH fork - 5.09.32.19
**GT++ Version** - 1.6.110-final, compiled master, and master with #196 
**IC2 Version:** industrialcraft-2-2.2.828a-experimental
Local server & client running as separate processes.

Both issue happen on 1.6.110-final as distributed by GTNH modpack on technics, also on a self compiled master branch (12cf6ccb2e0b4c8fd3e1f492de7720f64d7769f5), as well as master + PR #196 cherry picked & compiled.

**Issue 1:**  When making Grisium the machine will run for 2 cycles, outputting 14,000L of molten grisium, and then stop.  Hitting the controller with a soft mallet will cycle the controller green and then red again, consuming the materials but not producing any results.  It will work again for 2 cycles after breaking the controller, replacing it, and performing maintenance.  

**Issue 2:**  This one's a bit weird -- When clicking on the controller the item in my upper left inventory shows up as inserted into controller, and all items in my inventory shift one to the left. 

_Screenshots for issue 2:_

Normal Inventory, right before right clicking the controller
![inventory_normal](https://user-images.githubusercontent.com/1894689/35490179-a4008824-0452-11e8-98f4-e4e1e44479f8.png)

Inventory, directly after right clicking the controller
![inventory_after_clicking_controller](https://user-images.githubusercontent.com/1894689/35490181-ab464952-0452-11e8-956f-12c43637cf43.png)

_Notes for issue 2_

- I restarted, same issue. 
- I did not experience the same issue with the ore washing plat controller.
- I cheated in some other type of gt++ controllers, and did not notice the same issue. (was not exhaustive, did like 8)
- I cheated in another alloy blast smelter controller, placed it by itself - same thing happened.
- It appears to be some sort of sync issue -- have not yet tested in single player:  Clicking on another multiblock controller immediately causes my inventory to show up correctly.  Using a tool causes it to re-appear as the what it was before clicking on the smelter controller.

**Comment by draknyte1** [comment] 2018-01-29 01:58
Interesting.
We've had some good bugs come out of the woodwork lately.

**Comment by mitchej123** [comment] 2018-01-29 04:14
Molten zirconium carbide (120 seconds) went for about 100 seconds and then stopped, no output.

Molten silicon carbide (80 seconds) went one full cycle, and then 20 seconds into the second cycle before stopping and exhibiting the same behavior.

Debug scanner right before & after it crapped out:

```
[19:57:54] [Client thread/INFO]: [CHAT] ----- X: §b-69§r Y: §b75§r Z: §b-1034§r D: §b0§r -----
[19:57:54] [Client thread/INFO]: [CHAT] Name: §9industrialsalloyamelter.controller.tier.single§r MetaData: §b2§r
[19:57:54] [Client thread/INFO]: [CHAT] Hardness: §e1.0§r Blast Resistance: §e10.0§r
[19:57:54] [Client thread/INFO]: [CHAT] Progress/Load: §a391§r / §e1,600§r
[19:57:54] [Client thread/INFO]: [CHAT] Owned by: §9<PROFILE NAME>§r
[19:57:54] [Client thread/INFO]: [CHAT] Progress:
[19:57:54] [Client thread/INFO]: [CHAT] 19secs
[19:57:54] [Client thread/INFO]: [CHAT] 80secs
[19:57:54] [Client thread/INFO]: [CHAT] Efficiency:
[19:57:54] [Client thread/INFO]: [CHAT] 100.0%
[19:57:54] [Client thread/INFO]: [CHAT] Problems:
[19:57:54] [Client thread/INFO]: [CHAT] 0
[19:57:54] [Client thread/INFO]: [CHAT] Pollution in Chunk: §c3918915§r gibbl
[19:57:54] [Client thread/INFO]: [CHAT] Meta-ID: §9810§r§a valid§r 
[19:57:54] [Client thread/INFO]: [CHAT] Average CPU-load of ~0.08ms since 25 ticks.
[19:57:54] [Client thread/INFO]: [CHAT] Is accessible for you
[19:57:54] [Client thread/INFO]: [CHAT] Machine is §aactive§r

[19:57:55] [Client thread/INFO]: [CHAT] ----- X: §b-69§r Y: §b75§r Z: §b-1034§r D: §b0§r -----
[19:57:55] [Client thread/INFO]: [CHAT] Name: §9industrialsalloyamelter.controller.tier.single§r MetaData: §b2§r
[19:57:55] [Client thread/INFO]: [CHAT] Hardness: §e1.0§r Blast Resistance: §e10.0§r
[19:57:55] [Client thread/INFO]: [CHAT] Owned by: §9<PROFILE NAME>§r
[19:57:55] [Client thread/INFO]: [CHAT] Progress:
[19:57:55] [Client thread/INFO]: [CHAT] 0secs
[19:57:55] [Client thread/INFO]: [CHAT] 0secs
[19:57:55] [Client thread/INFO]: [CHAT] Efficiency:
[19:57:55] [Client thread/INFO]: [CHAT] 0.0%
[19:57:55] [Client thread/INFO]: [CHAT] Problems:
[19:57:55] [Client thread/INFO]: [CHAT] 0
[19:57:55] [Client thread/INFO]: [CHAT] Pollution in Chunk: §c3949776§r gibbl
[19:57:55] [Client thread/INFO]: [CHAT] Meta-ID: §9810§r§a valid§r 
[19:57:55] [Client thread/INFO]: [CHAT] Average CPU-load of ~0.04ms since 25 ticks.
[19:57:55] [Client thread/INFO]: [CHAT] Is accessible for you
[19:57:55] [Client thread/INFO]: [CHAT] Machine is §cinactive§r
```

**Comment by draknyte1** [comment] 2018-01-29 10:18
This should be resolved if you build again from master.

**Comment by codewarrior0** [comment] 2018-01-29 10:22
Is the items-shifting-around in the ABF GUI fixed, too?

**Comment by draknyte1** [comment] 2018-01-29 10:24
> Is the items-shifting-around in the ABF GUI fixed, too?

No, but I know what the issue is.
It's why I opened #199.

Will do that before building.

**Comment by mitchej123** [comment] 2018-01-30 02:55
Issue 1 seems resolved on master.  Also the pollution isn't going super crazy (went up to almost 4mil last time from 600k).

**Comment by draknyte1** [comment] 2018-02-04 16:34
Issue 2 has been resolved via https://github.com/draknyte1/GTplusplus/commit/522ec22b61f54ccbb9c494d69f466f9b56d3bd84.

**Closed by draknyte1** 2018-02-04 16:34 UTC
Labels: To investigate, bug, minor
